version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - cognia_static_volume:/cognia/static
      - cognia_files_volume:/cognia/files
    networks:
      - nginx_network

volumes:
  cognia_static_volume:
    external: true
  cognia_files_volume:
    external: true
networks:
  nginx_network:
    external: true