version: '3'

services:
  cognia:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/cognia
      - cognia_static_volume:/cognia/static
      - cognia_files_volume:/cognia/files
    restart: always
    ports:
      - "8000:8000"
    networks:
      - cognia_network
      - nginx_network
    depends_on:
      - cognia_postgresql
  cognia_postgresql:
    image: postgres:12
    container_name: cognia_postgresql
    volumes:
      - cognia_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - cognia_network

volumes:
  cognia_postgresql:
    external: true
  cognia_static_volume:
    external: true
  cognia_files_volume:
    external: true
networks:
  cognia_network:
    external: true
  nginx_network:
    external: true
