# Generated by Django 3.2.11 on 2022-06-25 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mbti',
        ),
    ]
