# Generated by Django 3.2.11 on 2022-06-25 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_remove_userprofile_mbti'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mbti',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='persona.mbti'),
        ),
    ]
