# Generated by Django 3.2.11 on 2022-06-25 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_alter_userprofile_mbti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='mbti',
        ),
    ]
